#!/usr/bin/env bash
set -eu

cd $HOME

if [ -d "$HOME/dotfiles" ]; then
  echo "Folder dotfiles already exists. Moving to next step..."
else
  echo "Cloning dotfiles repository ..."
  git clone https://github.com/willmendesneto/dotfiles.git ~/dotfiles
fi

echo "Installing Homebrew..."

command -v brew >/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Running 'install.sh' script to install dependencies..."

SKIP_BREW_CLEANUP="false"
DEFAULT_RUBY_VERSION="2.3.3"
DEFAULT_NODE_VERSION="v14.7.3"

for i in "$@"
do
  case $i in
    --ruby-version=*)
    DEFAULT_RUBY_VERSION="${i#*=}"
    shift # past argument=value
    ;;
    --node-version=*)
    DEFAULT_NODE_VERSION="${i#*=}"
    shift # past argument=value
    ;;
    --skip-brew-cleanup=*)
    SKIP_BREW_CLEANUP="${i#*=}"
    shift # past argument=value
    ;;
    --default)
    shift # past argument with no value
    ;;
    *)
      # unknown option
    ;;
  esac
done

chmod +x ./dotfiles/install.sh

DEFAULT_RUBY_VERSION=$DEFAULT_RUBY_VERSION \
DEFAULT_NODE_VERSION=$DEFAULT_NODE_VERSION \
SKIP_BREW_CLEANUP=$SKIP_BREW_CLEANUP ./dotfiles/install.sh

tput setaf 3;
echo "

-- ALL INSTALLED. NOW YOU ARE GOOD TO GO 👏👏👏👏 --
Please check your '~/.zshrc' and update the values of your environment variables

-----------------------------------------------------------------------------------
NPM_EMAIL='<add-your-npm-email-here>' with the your NPM email
NPM_PASSWORD='<add-your-npm-password-here>' with the your NPM email
NPM_USERNAME='<add-your-npm-username-here>' with the your NPM username
GITHUB_DIFF_TOKEN='<add-your-token-here>' with the your Github token.
-----------------------------------------------------------------------------------

** How to create a personal access token with the *notifications* and *repo* permissions. https://github.com/settings/tokens/new?scopes=notifications,repo
-- AFTER THAT, PLEASE RESTART YOUR CLI AND START CODING! --

"
tput sgr0;
