alias nv="node -v"
alias ni="npm install"
alias nt="npm test"
alias ns="npm start"
alias nl="npm link"
alias nr="npm run"
alias ne2e="npm run e2e"

# YARN aliases
alias yarnglobal="npm install -g yarn"
alias yw="yarn run watch"
alias yt="yarn run test"
alias yl="yarn link"
alias ytdd="yarn run tdd"
alias yr="yarn run"
alias ye2e="yarn run test:e2e"
